option(WITH_SYSTEM_ASIO "Use system Asio library" OFF)
option(WITH_SYSTEM_EXPAT "Use system Expat library" OFF)
option(WITH_SYSTEM_ZLIB "Use system Zlib library" OFF)
option(WITH_SYSTEM_JPEG "Use system JPEG library" OFF)
option(WITH_SYSTEM_FLAC "Use system FLAC library" OFF)
option(WITH_SYSTEM_SQLITE3 "Use system SQLite library" OFF)
option(WITH_SYSTEM_PORTMIDI "Use system PortMidi library" OFF)
option(WITH_SYSTEM_PORTAUDIO "Use system PortAudio library" OFF)
option(WITH_SYSTEM_LUA "Use system LUA library" OFF)
option(WITH_SYSTEM_UTF8PROC "Use system utf8proc library" OFF)
option(WITH_SYSTEM_GLM "Use system glm library" OFF)
option(WITH_SYSTEM_RAPIDJSON "Use system rapidjson library" OFF)
option(WITH_SYSTEM_PUGIXML "Use system pugixml library" OFF)

if(NOT WITH_SYSTEM_EXPAT)
    add_project_to_group_and_include(3rdparty expat scripts/cmake/3rdparty/expat.cmake)
endif()
if(NOT WITH_SYSTEM_ZLIB)
    add_project_to_group_and_include(3rdparty zlib scripts/cmake/3rdparty/zlib.cmake)
endif()
add_project_to_group_and_include(3rdparty softfloat scripts/cmake/3rdparty/softfloat.cmake)
add_project_to_group_and_include(3rdparty softfloat3 scripts/cmake/3rdparty/softfloat3.cmake)
if(NOT WITH_SYSTEM_JPEG)
    add_project_to_group_and_include(3rdparty jpeg scripts/cmake/3rdparty/jpeg.cmake)
endif()
if(NOT WITH_SYSTEM_FLAC)
    add_project_to_group_and_include(3rdparty flac scripts/cmake/3rdparty/flac.cmake)
endif()
add_project_to_group_and_include(3rdparty 7z scripts/cmake/3rdparty/7z.cmake)
if(NOT WITH_SYSTEM_LUA)
    add_project_to_group_and_include(3rdparty lua scripts/cmake/3rdparty/lua.cmake)
endif()
add_project_to_group_and_include(3rdparty lualibs scripts/cmake/3rdparty/lualibs.cmake)
if(NOT WITH_SYSTEM_SQLITE3)
    add_project_to_group_and_include(3rdparty sqlite3 scripts/cmake/3rdparty/sqlite3.cmake)
endif()
if(NOT WITH_SYSTEM_PORTMIDI)
    add_project_to_group_and_include(3rdparty portmidi scripts/cmake/3rdparty/portmidi.cmake)
endif()
add_project_to_group_and_include(3rdparty bx scripts/cmake/3rdparty/bx.cmake)
add_project_to_group_and_include(3rdparty bimg scripts/cmake/3rdparty/bimg.cmake)
add_project_to_group_and_include(3rdparty bgfx scripts/cmake/3rdparty/bgfx.cmake)
if(NOT WITH_SYSTEM_PORTAUDIO)
    add_project_to_group_and_include(3rdparty portaudio scripts/cmake/3rdparty/portaudio.cmake)
endif()
if(NOT ${OSD} STREQUAL "uwp")
    add_project_to_group_and_include(3rdparty linenoise scripts/cmake/3rdparty/linenoise.cmake)
endif()
if(NOT WITH_SYSTEM_UTF8PROC)
    add_project_to_group_and_include(3rdparty utf8proc scripts/cmake/3rdparty/utf8proc.cmake)
endif()
add_project_to_group_and_include(3rdparty wdlfft scripts/cmake/3rdparty/wdlfft.cmake)
add_project_to_group_and_include(3rdparty ymfm scripts/cmake/3rdparty/ymfm.cmake)
if(NOT FORCE_DRC_C_BACKEND)
    add_project_to_group_and_include(3rdparty asmjit scripts/cmake/3rdparty/asmjit.cmake)
endif()
