add_project_to_group_and_include(3rdparty expat scripts/cmake/3rdparty/expat.cmake)
add_project_to_group_and_include(3rdparty zlib scripts/cmake/3rdparty/zlib.cmake)
add_project_to_group_and_include(3rdparty softfloat scripts/cmake/3rdparty/softfloat.cmake)
add_project_to_group_and_include(3rdparty softfloat3 scripts/cmake/3rdparty/softfloat3.cmake)
add_project_to_group_and_include(3rdparty jpeg scripts/cmake/3rdparty/jpeg.cmake)
add_project_to_group_and_include(3rdparty flac scripts/cmake/3rdparty/flac.cmake)
add_project_to_group_and_include(3rdparty 7z scripts/cmake/3rdparty/7z.cmake)
add_project_to_group_and_include(3rdparty lua scripts/cmake/3rdparty/lua.cmake)
add_project_to_group_and_include(3rdparty lualibs scripts/cmake/3rdparty/lualibs.cmake)
add_project_to_group_and_include(3rdparty sqlite3 scripts/cmake/3rdparty/sqlite3.cmake)
add_project_to_group_and_include(3rdparty portmidi scripts/cmake/3rdparty/portmidi.cmake)
add_project_to_group_and_include(3rdparty bx scripts/cmake/3rdparty/bx.cmake)
add_project_to_group_and_include(3rdparty bimg scripts/cmake/3rdparty/bimg.cmake)
add_project_to_group_and_include(3rdparty bgfx scripts/cmake/3rdparty/bgfx.cmake)
add_project_to_group_and_include(3rdparty portaudio scripts/cmake/3rdparty/portaudio.cmake)
if (NOT ${OSD} STREQUAL "uwp")
    add_project_to_group_and_include(3rdparty linenoise scripts/cmake/3rdparty/linenoise.cmake)
endif()
add_project_to_group_and_include(3rdparty utf8proc scripts/cmake/3rdparty/utf8proc.cmake)
add_project_to_group_and_include(3rdparty wdlfft scripts/cmake/3rdparty/wdlfft.cmake)
add_project_to_group_and_include(3rdparty ymfm scripts/cmake/3rdparty/ymfm.cmake)
if(NOT FORCE_DRC_C_BACKEND)
    add_project_to_group_and_include(3rdparty asmjit scripts/cmake/3rdparty/asmjit.cmake)
endif()
