add_project_to_group_and_include(tools romcmp scripts/cmake/tools/romcmp.cmake)
add_project_to_group_and_include(tools chdman scripts/cmake/tools/chdman.cmake)
add_project_to_group_and_include(tools jedutil scripts/cmake/tools/jedutil.cmake)
add_project_to_group_and_include(tools unidasm scripts/cmake/tools/unidasm.cmake)
add_project_to_group_and_include(tools ldresample scripts/cmake/tools/ldresample.cmake)
add_project_to_group_and_include(tools ldverify scripts/cmake/tools/ldverify.cmake)
add_project_to_group_and_include(tools regrep scripts/cmake/tools/regrep.cmake)
add_project_to_group_and_include(tools srcclean scripts/cmake/tools/srcclean.cmake)
add_project_to_group_and_include(tools split scripts/cmake/tools/split.cmake)
add_project_to_group_and_include(tools pngcmp scripts/cmake/tools/pngcmp.cmake)
add_project_to_group_and_include(tools nltool scripts/cmake/tools/nltool.cmake)
add_project_to_group_and_include(tools nlwav scripts/cmake/tools/nlwav.cmake)
add_project_to_group_and_include(tools castool scripts/cmake/tools/castool.cmake)
add_project_to_group_and_include(tools floptool scripts/cmake/tools/floptool.cmake)
add_project_to_group_and_include(tools imgtool scripts/cmake/tools/imgtool.cmake)
if(${OSD} STREQUAL "sdl")
    add_project_to_group_and_include(tools testkeys scripts/cmake/tools/testkeys.cmake)
endif()
